---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: {{label}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{label}}
  template:
    metadata:
      labels:
        app: {{label}}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: {{port}}
